# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank
first_name: Athresh
middle_name:
last_name: Karanam
contact_note: >
  Email is the best way to reach me.
description: >
  Personal academic website of Athresh Karanam.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: athresh karanam, academic website
lang: en
icon: ⚛️

url: https://athresh.github.io
baseurl:
last_updated: false
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
bib_search: false
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /:collection/:title/

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages"]
exclude:
  - bin/
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - package-lock.json
  - purgecss.config.js
  - requirements.txt
  - vendor
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-email-protect
  - jekyll-get-json
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-terser
  - jemoji

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  compress_css: false
  compress_javascript: false

# -----------------------------------------------------------------------------
# Terser
# -----------------------------------------------------------------------------

terser:
  compress:
    drop_console: true

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Karanam]
  first_name: [Athresh, A.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_link: Details

  query: "@*"
  group_by: year
  group_order: descending

filtered_bibtex_keywords:
  [
    abbr,
    abstract,
    additional_info,
    altmetric,
    annotation,
    arxiv,
    award,
    award_name,
    bibtex_show,
    blog,
    code,
    google_scholar_id,
    html,
    inspirehep_id,
    pdf,
    poster,
    preview,
    pubtype,
    selected,
    slides,
    supp,
    video,
    website,
  ]

max_author_limit: 3
more_authors_animation_delay: 10
enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Optional site features currently used
# -----------------------------------------------------------------------------

enable_math: true
enable_darkmode: true
enable_navbar_social: false
enable_medium_zoom: true
enable_progressbar: true
enable_video_embedding: false

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

third_party_libraries:
  download: false
  google_fonts:
    url:
      fonts: "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap"
  jquery:
    integrity:
      js: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    url:
      js: "https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"
  mathjax:
    integrity:
      js: "sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI="
    url:
      js: "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js"
  mdb:
    integrity:
      css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
      js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
    url:
      css: "https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/css/mdb.min.css"
      js: "https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/js/mdb.min.js"
  medium_zoom:
    integrity:
      js: "sha256-ZgMyDAIYDYGxbcpJcfUnYwNevG/xi9OHKaR/8GK+jWc="
    url:
      js: "https://cdn.jsdelivr.net/npm/medium-zoom@1.1.0/dist/medium-zoom.min.js"
  photoswipe:
    url:
      css: "https://cdn.jsdelivr.net/npm/photoswipe@5.4.4/dist/photoswipe.min.css"
  polyfill:
    url:
      js: "https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json

jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
